
export const MEMBER_ROLE_PARTIES = [
  'No Party Data',     // for error handling
  'Democrat',
  'Republican',
  'Populist',
  'Unionist',
  'Whig',
  'Jackson',
  'Federalist',
  'Ind. Republican-Democrat',
  'Nullifier',
  'Independent',
  'Liberal Republican',
  'Adams',
  'Popular Democrat',
  'Ind. Democrat',
  'Pro-Administration',
  'Anti-Lecompton Democrat',
  'Jacksonian',
  'Anti-Jacksonian',
  'Unconditional Unionist',
  'Anti-Administration',
  'Law and Order',
  'Adams Democrat',
  'National Greenbacker',
  'American',
  'New Progressive',
  'Anti Masonic',
  'Democratic Republican',
  'Silver Republican',
  'Progressive',
  'Free Silver',
  'Anti Jacksonian',
  'Ind. Republican',
  'Free Soil',
  'Nonpartisan',
  'Republican-Conservative',
  'Readjuster',
  'States Rights',
  'Conservative Republican',
  'Union Labor',
  'Ind. Whig',
  'Unknown',
  'Readjuster Democrat',
  'American Labor',
  'Conservative',
  'Coalitionist',
  'Crawford Republican',
  'Farmer-Labor',
  'Liberal',
  'AL',
  'Union',
  'Anti Jackson',
  'Liberty',
  'Union Democrat',
  'Anti Mason',
  'Anti-administration',
  'Pro-administration',
  'Democratic and Union Labor',
  'Prohibitionist',
  'Constitutional Unionist',
  'Socialist',
  'Silver',
  'Jackson Republican',
  'Independent Democrat',
  'Jacksonian Republican',
  'Progressive Republican',
  'Democrat-Liberal',
 ];

export const STATES = ['ID' , 'VA' , 'IN' , 'SD' , 'ME' , 'NV' , 'AK' ,
  'WV' , 'IA' , 'SC' , 'WA' , 'NH' , 'OK' , 'LA' , 'NY' , 'ND' , 'NJ' , 'MO' , 'KS' ,
  'CT' , 'RI' , 'UT' , 'WY' , 'OR' , 'AL' , 'MN' , 'NE' , 'TX' , 'NC' , 'CA' , 'OH' ,
  'KY' , 'MT' , 'CO' , 'MA' , 'MD' , 'AZ' , 'VT' , 'NM' , 'PA' , 'DE' , 'TN' , 'WI' ,
  'MS' , 'GA' , 'AR' , 'FL' , 'HI' , 'MI' , 'IL'];

export const TERRITORIES = ['MP' , 'GU' , 'AS' , 'VI' , 'PI' , 'DK'];

export const REGIONS = ['PI' , 'DK'];
